---
- include_tasks: install_php_from_ppa_ondrej.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: install_php_from_ppa_ondrej.yml
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: download installation shell for composer
  uri:
    url: https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer
    dest: /tmp/install_composer.php
    creates: /tmp/install_composer.php

- name: install composer
  command: php /tmp/install_composer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: set symlink for composer
  file:
    path: /usr/bin/composer
    state: link
    src: /usr/local/bin/composer
    owner: root
    group: root
